plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Red vs Blue
description: Model to predict the outcome of a League of Legends' match based on the first 15 minutes of the game